// General
export const NOT_ACTIVE = "NOT_ACTIVE"
export const ACTIVE = "ACTIVE"
export const COMPLETE = "COMPLETE"
export const FAIL = "FAIL"

// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST'
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS'
export const OTP_VERIFY_FAIL = 'OTP_VERIFY_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SET_LOGIN_REQUEST_STATUS = 'SET_LOGIN_REQUEST_STATUS'
export const SET_LOGOUT_REQUEST_STATUS = 'SET_LOGOUT_REQUEST_STATUS'
export const SET_REGISTER_REQUEST_STATUS = 'SET_REGISTER_REQUEST_STATUS'
export const SET_VERIFY_REQUEST_STATUS = 'SET_VERIFY_REQUEST_STATUS' 

// Product
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';

// Category
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const GET_CATEGORIES = 'GET_CATEGORIES';

// Cart
export const CART_LOADING = 'CART_LOADING';
export const GET_CART = 'GET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';

// Order
export const ORDERS_LOADING = 'ORDERS_LOADING';
export const GET_ORDERS = 'GET_ORDERS';

export const CHECKOUT = 'CHECKOUT';

export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';